language: node_js
node_js:
- node
notifications:
  slack:
    secure: 3CIoX+F5cEadScG6tmUieXcEMG2VwUIM3rmvgT/5db0SoHBUsRa4PNrmdf9lcu06ohZI8nwq8mHXfYBS7enPzm9Gw5WdTC2L2DVbmXTbyv5cyWUReuHe1mrxTJeIgaUQfB0d4WTMo5UQL+gF1TUJe2rDtePXtcsRKKToWypSAZ3aPFvfeQwPd4O2JJJIr+ZCqbqNZ0ca6x13IPG+z8DWpEmZ1A7gnaK2s41r+4kN7XNpiSdRy6H3yEdLoh/kgsk5vQmUGEGEBVch4Z7f8zloskOpF3eMCip9+fFSU3mV6Vk09QiIp/3PBV5jvy8b5OHVx+dq679sAThGFYS/MpRBAjpBsw5cLmuBmk4fqUj+QQkolJZVnsM+iPHLzrd1oj+ePBDI4dp69t3kxPlu8cezORX9fl7m+AedmR8MV+yufk+8jd6xfySK+sNCKfLr/Iaw5OHnUZfuU+SvBZIRMdYBlMczzTotrg7avDUw4gJK1D6zOAGMmofba/8EqrjDSFLiKbvkQUfhkguusWED0hPAo/YGCXgMSSQZqI0YMTzz5M1oNJpC8klZTqU2f9ZRXODoGZnkAfr3z7sO5whaClIuzsi0Ya/TVYcWLtaUoT43PbddcAA5P8ysbiBfN2ajaYyyLWXsf4//ZMOWFfjcomCPEDlwxfVgABfSD06QU/NzoBU=
